FROM nodered/node-red:latest

RUN npm install --unsafe-perm --no-update-notifier --no-fund --omit=dev \
  @flowfuse/node-red-dashboard \
  node-red-contrib-crypto-js \
  node-red-node-mongodb \
  node-red-node-email \
  node-red-dashboard